services:
  todo-app:
    build: .
    container_name: todo-list
    ports:
      - "3000:3000"
    volumes:
      - todo-data:/app/data
    restart: unless-stopped

volumes:
  todo-data:
    driver: local 